const {baseConfig} = require('@virmator/spellcheck/configs/cspell.config.base.cjs');

module.exports = {
    ...baseConfig,
    ignorePaths: [
        ...baseConfig.ignorePaths,
    ],
    words: [
        ...baseConfig.words,
        'cqmin',
        'cubehelix',
        'culori',
        'darkgray',
        'darkgrey',
        'darkslategray',
        'darkslategrey',
        'dimgray',
        'dimgrey',
        'dlab',
        'dlch',
        'lchuv',
        'lightgoldenrodyellow',
        'lightgray',
        'lightslategray',
        'lightslategrey',
        'lrgb',
        'okhsl',
        'okhsv',
        'oklab',
        'oklch',
        'prophoto',
        'slategray',
        'slategrey',
    ],
};
